### ISSUE TITLE
Create GitPod configuration

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/examples-lingua-franca#18]
People should be able to launch a GitPod from the `README.md` that comes with all LF dev dependencies preinstalled.

**Comment by axmmisaka** [comment]
I am biased and I prefer [GitHub Codespace](https://github.com/features/codespaces) for better integration; I did some experiments and it should be able to plug and play now
https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=568328121

Now, of course, the issue is do we want to just update the whole repo's structure, or do we make a separate branch for codespace, or a separate repo?

**Comment by lhstrh** [comment]
I'm not against Code Spaces, but I don't think it's compatible with our VS Code extension. See https://github.com/lf-lang/vscode-lingua-franca/issues/78. My impression was that Git Pods do not have this limitation, but I might be wrong about that.

**Comment by axmmisaka** [comment]
> I'm not against Code Spaces, but I don't think it's compatible with our VS Code extension. See [lf-lang/vscode-lingua-franca#78](https://github.com/lf-lang/vscode-lingua-franca/issues/78). My impression was that Git Pods do not have this limitation, but I might be wrong about that.

It would work because it is essentially a docker instance running with a VSCode front-end exposed (so `lfc` which is required can be run) instead of an enhanced code editor.
![image](https://user-images.githubusercontent.com/6500159/202922695-242b1c32-8f13-42c3-a639-1d31cdca7d59.png)
But I thought about it and maybe we can have both!

**Comment by lhstrh** [comment]
How are you able to run the VS Code extension in Codespaces considering the issue discussed in https://github.com/lf-lang/vscode-lingua-franca/issues/78? :thinking:

**Comment by lhstrh** [comment]
Oh, I guess I confused `github.dev` and CodeSpaces; I thought they were based on the same technology, but I guess they are not! In that case, I agree with you let's set up CodeSpaces first...

**Comment by lhstrh** [comment]
@rcakella, could we incorporate your GitPod configuration into our playground?

**Comment by lhstrh** [comment]
A GitPod configuration is now available on the [playground](https://github.com/lf-lang/lingua-franca-playground).
