### ISSUE TITLE
Examples failing

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/examples-lingua-franca#53]
A number of examples are failing due to issues that I do not know how to fix:

* C/src/ProtocolBuffers/HelloProtocolBuffers.lf
This one fails because protobufs is not installed in CI.  How to install it?  The instructions for installation are included in the .lf file.

* C/src/DistributedHelloWorld/HelloWorldDecentralized.lf
  C/src/DistributedHelloWorld/HelloWorldDecentralizedSTP.lf
These fail because of a bug in fedgen, reported in issue 1733 in lingua-franca: https://github.com/lf-lang/lingua-franca/issues/1733. This bug needs to be fixed before a release.

There also seems to be a problem with memory management. With several examples, I get the following warning on exit:
```
WARNING: Memory allocated for messages has not been freed.
WARNING: Number of unfreed messages: 3.
```
For example, C/src/train-door/TrainDoorAsymetric.lf gives this.

**Comment by lhstrh** [comment]
I could add these dependencies in the CI workflows, but for these examples to work on the [playground](https://github.com/lf-lang/lingua-franca-playground), the docker image used there will also need to have those dependencies installed. So what I'm thinking is that we should use the same docker image in CI and manage the dependencies there. Perhaps @axmmisaka could help us with since he's also the one who set up the playground.

**Comment by lhstrh** [comment]
>     * C/src/DistributedHelloWorld/HelloWorldDecentralized.lf
This is fixed in https://github.com/lf-lang/lingua-franca/issues/1733.
